# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  # Ruff linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.13
    hooks:
      # Run the linter
      - id: ruff
        name: ruff-lint
        args: [--fix]
        types: [python]
      # Run the formatter
      - id: ruff-format
        name: ruff-format
        types: [python]

  # Additional quality checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Basic file checks
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
        args: ['--maxkb=50000']  # 50MB limit

      # Python specific checks
      - id: check-ast
      - id: debug-statements
      - id: name-tests-test
        args: ['--pytest-test-first']

      # Git checks
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
        args: ['-c', 'pyproject.toml']
        additional_dependencies: ["bandit[toml]"]

# Configure pre-commit to run on all files by default
default_install_hook_types: [pre-commit, pre-push]

# Skip certain files/patterns
exclude: |
  (?x)(
    ^extra/models/.*\.py$ |  # Skip tinygrad model files
    ^\.git/.*$ |             # Skip git files
    ^__pycache__/.*$ |       # Skip cache
    ^\.venv/.*$ |            # Skip virtual environment
    ^build/.*$ |             # Skip build artifacts
    ^dist/.*$                # Skip distribution files
  )

# Minimum pre-commit version
minimum_pre_commit_version: '3.0.0'