name: Lint and Format

on:
  push:
  pull_request:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        enable-cache: true

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync --dev

    - name: Run Ruff linter
      run: uv run ruff check .

    - name: Run Ruff formatter
      run: uv run ruff format --check .