name: Code Quality

on:
  push:
  pull_request:

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        enable-cache: true

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync --dev

    - name: Run quality checks
      run: |
        # File quality checks
        uv run python -m pre_commit_hooks.trailing_whitespace --fix $(find . -name "*.py" -o -name "*.yml" -o -name "*.yaml" -o -name "*.toml" -o -name "*.json" -o -name "*.md")
        uv run python -m pre_commit_hooks.end_of_file_fixer $(find . -name "*.py" -o -name "*.yml" -o -name "*.yaml" -o -name "*.toml" -o -name "*.json" -o -name "*.md")

        # Configuration validation
        uv run python -m pre_commit_hooks.check_yaml $(find . -name "*.yml" -o -name "*.yaml")
        uv run python -m pre_commit_hooks.check_toml $(find . -name "*.toml")
        uv run python -m pre_commit_hooks.check_json $(find . -name "*.json")

        # Git and Python checks
        uv run python -m pre_commit_hooks.check_merge_conflict $(find . -type f)
        uv run python -m pre_commit_hooks.check_case_conflict $(find . -type f)
        uv run python -m pre_commit_hooks.check_ast $(find . -name "*.py")
        uv run python -m pre_commit_hooks.debug_statements $(find . -name "*.py")